# Generated by Django 4.2.6 on 2023-10-29 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comp_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date completed'),
        ),
    ]
